version: '2'
services:
  echo-service:
    image: echo-service
    depends_on:
     - eureka-server
  eureka-server:
    image: eureka-server
    ports:
     - "8761:8761"
  zuul-server:
    image: zuul-server
    depends_on:
     - eureka-server
    ports:
     - "9090:9090"
