server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

zuul:
  prefix: /api
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'

spring:
  application:
    name: zuul-server