server:
  port: ${server_port:9098}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: echo-service
  devtools:
    remote:
      secret: mysecret

management:
  security:
    enabled: false